export default {
    spanish : {
        text_hello: 'Hola, soy',
        text_download: 'Descargar CV',
        scroll_down: 'Desplazarse hacia abajo',
        about_me: 'Sobre mi',
        experience: 'Experiencia',
        experience_years: 'años',
        projects: 'Proyectos',
        skills: 'Tecnologias',
        portfolio: 'Portafolio',
        dev: 'Jr Mobile & Web Developer en Garnet Technology',
        language_btn: 'Seleccion de idioma ',
        rigths_reserved:'Todos los derechos reservados',
        completed_projects: 'Proyectos completados',
        description_1: 'Comence mi camino como desarrollador como propuesta de ascenso en la compañia donde trabajo actualmente. Por supuesto acepte con emocion y es lo que me llevo donde estoy ahora. Alli estoy como desarrollador Web y Mobile (principalmente mobile en iOS & Android), trabajando en equipo con 2 colegas mas.',
        description_2: 'Disciplinado, comprometido, siempre buscando el progreso y la mejora. Esas son las principales caracteristicas que me definen. Como pasatiempo? Autos, futbol, entrenamiento y audio . No es la mejor descripcion, pero hacer autocritica siempre es dificil.',
        p1_description: "Web app utilizada internamente en la compañia por mis compañeros de trabajo para poder agilizar el servicio de soporte tecnico. Solo puedo mostrar imagenes",
        p2_description: "Esta es la app en la que estamos trabajando actualmente, todavia en desarrollo por lo cual no me es posible mostrar nada aun ;). Pero si puedo contarles que es la app del usuario final de la compañia",
        p3_description: "App de meetings",
        p4_description: "Mi primera pagina, hecha con el objetivo de expandir el alcence  y difusion del trabajo de mi padre"
    },
    english : {
        text_hello: "Hello I'm",
        text_download: 'Download CV',
        scroll_down: 'Scoll Down',
        about_me: 'About Me',
        experience: 'Experience',
        experience_years: 'years',
        projects: 'Projects',
        skills: 'Skills',
        portfolio: 'Portfolio',
        dev: 'Jr Mobile & Web Developer at Garnet Technology',
        language_btn: 'Language selector',
        rigths_reserved:'All rights reserved',
        completed_projects: 'Completed Projects',
        description_1: "I started my journey as a developer as a promotion proposal in the company where I currently work. Of course I accepted with emotion and that's what took me to where I am now. I work as a Web and Mobile developer (mainly mobile in iOS & Android), working in a team with 2 other colleagues.",
        description_2: "Disciplined, committed, always looking for progress and improvement. Those are the main characteristics that define me. As a hobby? Cars, football, training and audio. It's not the best description, but self-criticism is always difficult.",
        p1_description: "Web app used internally in the company by my co-workers to speed up the technical support service. I can only show pictures",
        p2_description:"This is the app we are currently working on, still in development so it is not possible for me to show anything yet ;). But I can tell you that it is the company's end user app",
        p3_description: "Meeting App",
        p4_description: "My first page, made with the aim of expanding the reach and dissemination of my father's work"
    },
    latin: "AUT CONSEQUOR AUT MORIOR" 
}